export const TIMEZONES: Record<string, string> = {
  'Africa/Abidjan': '(GMT+00:00) Africa/Abidjan',
  'Africa/Algiers': '(GMT+01:00) Africa/Algiers',
  'Africa/Bissau': '(GMT+00:00) Africa/Bissau',
  'Africa/Cairo': '(GMT+02:00) Africa/Cairo',
  'Africa/Casablanca': '(GMT+00:00) Africa/Casablanca',
  'Africa/Ceuta': '(GMT+01:00) Africa/Ceuta',
  'Africa/El_Aaiun': '(GMT+00:00) Africa/El_Aaiun',
  'Africa/Johannesburg': '(GMT+02:00) Africa/Johannesburg',
  'Africa/Juba': '(GMT+02:00) Africa/Juba',
  'Africa/Khartoum': '(GMT+02:00) Africa/Khartoum',
  'Africa/Lagos': '(GMT+01:00) Africa/Lagos',
  'Africa/Maputo': '(GMT+02:00) Africa/Maputo',
  'Africa/Monrovia': '(GMT+00:00) Africa/Monrovia',
  'Africa/Nairobi': '(GMT+03:00) Africa/Nairobi',
  'Africa/Ndjamena': '(GMT+01:00) Africa/Ndjamena',
  'Africa/Sao_Tome': '(GMT+00:00) Africa/Sao_Tome',
  'Africa/Tripoli': '(GMT+02:00) Africa/Tripoli',
  'Africa/Tunis': '(GMT+01:00) Africa/Tunis',
  'Africa/Windhoek': '(GMT+01:00) Africa/Windhoek',
  'America/Adak': '(GMT-10:00) America/Adak',
  'America/Anchorage': '(GMT-09:00) America/Anchorage',
  'America/Araguaina': '(GMT-03:00) America/Araguaina',
  'America/Argentina/Buenos_Aires': '(GMT-03:00) America/Argentina/Buenos_Aires',
  'America/Argentina/Catamarca': '(GMT-03:00) America/Argentina/Catamarca',
  'America/Argentina/Cordoba': '(GMT-03:00) America/Argentina/Cordoba',
  'America/Argentina/Jujuy': '(GMT-03:00) America/Argentina/Jujuy',
  'America/Argentina/La_Rioja': '(GMT-03:00) America/Argentina/La_Rioja',
  'America/Argentina/Mendoza': '(GMT-03:00) America/Argentina/Mendoza',
  'America/Argentina/Rio_Gallegos': '(GMT-03:00) America/Argentina/Rio_Gallegos',
  'America/Argentina/Salta': '(GMT-03:00) America/Argentina/Salta',
  'America/Argentina/San_Juan': '(GMT-03:00) America/Argentina/San_Juan',
  'America/Argentina/San_Luis': '(GMT-03:00) America/Argentina/San_Luis',
  'America/Argentina/Tucuman': '(GMT-03:00) America/Argentina/Tucuman',
  'America/Argentina/Ushuaia': '(GMT-03:00) America/Argentina/Ushuaia',
  'America/Asuncion': '(GMT-04:00) America/Asuncion',
  'America/Bahia': '(GMT-03:00) America/Bahia',
  'America/Bahia_Banderas': '(GMT-06:00) America/Bahia_Banderas',
  'America/Barbados': '(GMT-04:00) America/Barbados',
  'America/Belem': '(GMT-03:00) America/Belem',
  'America/Belize': '(GMT-06:00) America/Belize',
  'America/Boa_Vista': '(GMT-04:00) America/Boa_Vista',
  'America/Bogota': '(GMT-05:00) America/Bogota',
  'America/Boise': '(GMT-07:00) America/Boise',
  'America/Cambridge_Bay': '(GMT-07:00) America/Cambridge_Bay',
  'America/Campo_Grande': '(GMT-04:00) America/Campo_Grande',
  'America/Cancun': '(GMT-05:00) America/Cancun',
  'America/Caracas': '(GMT-04:00) America/Caracas',
  'America/Cayenne': '(GMT-03:00) America/Cayenne',
  'America/Chicago': '(GMT-06:00) America/Chicago',
  'America/Chihuahua': '(GMT-07:00) America/Chihuahua',
  'America/Costa_Rica': '(GMT-06:00) America/Costa_Rica',
  'America/Cuiaba': '(GMT-04:00) America/Cuiaba',
  'America/Danmarkshavn': '(GMT+00:00) America/Danmarkshavn',
  'America/Dawson': '(GMT-07:00) America/Dawson',
  'America/Dawson_Creek': '(GMT-07:00) America/Dawson_Creek',
  'America/Denver': '(GMT-07:00) America/Denver',
  'America/Detroit': '(GMT-05:00) America/Detroit',
  'America/Edmonton': '(GMT-07:00) America/Edmonton',
  'America/Eirunepe': '(GMT-05:00) America/Eirunepe',
  'America/El_Salvador': '(GMT-06:00) America/El_Salvador',
  'America/Fort_Nelson': '(GMT-07:00) America/Fort_Nelson',
  'America/Fortaleza': '(GMT-03:00) America/Fortaleza',
  'America/Glace_Bay': '(GMT-04:00) America/Glace_Bay',
  'America/Goose_Bay': '(GMT-04:00) America/Goose_Bay',
  'America/Grand_Turk': '(GMT-05:00) America/Grand_Turk',
  'America/Guatemala': '(GMT-06:00) America/Guatemala',
  'America/Guayaquil': '(GMT-05:00) America/Guayaquil',
  'America/Guyana': '(GMT-04:00) America/Guyana',
  'America/Halifax': '(GMT-04:00) America/Halifax',
  'America/Havana': '(GMT-05:00) America/Havana',
  'America/Hermosillo': '(GMT-07:00) America/Hermosillo',
  'America/Indiana/Indianapolis': '(GMT-05:00) America/Indiana/Indianapolis',
  'America/Indiana/Knox': '(GMT-06:00) America/Indiana/Knox',
  'America/Indiana/Marengo': '(GMT-05:00) America/Indiana/Marengo',
  'America/Indiana/Petersburg': '(GMT-05:00) America/Indiana/Petersburg',
  'America/Indiana/Tell_City': '(GMT-06:00) America/Indiana/Tell_City',
  'America/Indiana/Vevay': '(GMT-05:00) America/Indiana/Vevay',
  'America/Indiana/Vincennes': '(GMT-05:00) America/Indiana/Vincennes',
  'America/Indiana/Winamac': '(GMT-05:00) America/Indiana/Winamac',
  'America/Inuvik': '(GMT-07:00) America/Inuvik',
  'America/Iqaluit': '(GMT-05:00) America/Iqaluit',
  'America/Jamaica': '(GMT-05:00) America/Jamaica',
  'America/Juneau': '(GMT-09:00) America/Juneau',
  'America/Kentucky/Louisville': '(GMT-05:00) America/Kentucky/Louisville',
  'America/Kentucky/Monticello': '(GMT-05:00) America/Kentucky/Monticello',
  'America/La_Paz': '(GMT-04:00) America/La_Paz',
  'America/Lima': '(GMT-05:00) America/Lima',
  'America/Los_Angeles': '(GMT-08:00) America/Los_Angeles',
  'America/Maceio': '(GMT-03:00) America/Maceio',
  'America/Managua': '(GMT-06:00) America/Managua',
  'America/Manaus': '(GMT-04:00) America/Manaus',
  'America/Martinique': '(GMT-04:00) America/Martinique',
  'America/Matamoros': '(GMT-06:00) America/Matamoros',
  'America/Mazatlan': '(GMT-07:00) America/Mazatlan',
  'America/Menominee': '(GMT-06:00) America/Menominee',
  'America/Merida': '(GMT-06:00) America/Merida',
  'America/Metlakatla': '(GMT-09:00) America/Metlakatla',
  'America/Mexico_City': '(GMT-06:00) America/Mexico_City',
  'America/Miquelon': '(GMT-03:00) America/Miquelon',
  'America/Moncton': '(GMT-04:00) America/Moncton',
  'America/Monterrey': '(GMT-06:00) America/Monterrey',
  'America/Montevideo': '(GMT-03:00) America/Montevideo',
  'America/New_York': '(GMT-05:00) America/New_York',
  'America/Nipigon': '(GMT-05:00) America/Nipigon',
  'America/Nome': '(GMT-09:00) America/Nome',
  'America/Noronha': '(GMT-02:00) America/Noronha',
  'America/North_Dakota/Beulah': '(GMT-06:00) America/North_Dakota/Beulah',
  'America/North_Dakota/Center': '(GMT-06:00) America/North_Dakota/Center',
  'America/North_Dakota/New_Salem': '(GMT-06:00) America/North_Dakota/New_Salem',
  'America/Ojinaga': '(GMT-07:00) America/Ojinaga',
  'America/Panama': '(GMT-05:00) America/Panama',
  'America/Pangnirtung': '(GMT-05:00) America/Pangnirtung',
  'America/Paramaribo': '(GMT-03:00) America/Paramaribo',
  'America/Phoenix': '(GMT-07:00) America/Phoenix',
  'America/Port-au-Prince': '(GMT-05:00) America/Port-au-Prince',
  'America/Porto_Velho': '(GMT-04:00) America/Porto_Velho',
  'America/Puerto_Rico': '(GMT-04:00) America/Puerto_Rico',
  'America/Punta_Arenas': '(GMT-03:00) America/Punta_Arenas',
  'America/Rainy_River': '(GMT-06:00) America/Rainy_River',
  'America/Rankin_Inlet': '(GMT-06:00) America/Rankin_Inlet',
  'America/Recife': '(GMT-03:00) America/Recife',
  'America/Regina': '(GMT-06:00) America/Regina',
  'America/Resolute': '(GMT-06:00) America/Resolute',
  'America/Rio_Branco': '(GMT-05:00) America/Rio_Branco',
  'America/Santarem': '(GMT-03:00) America/Santarem',
  'America/Santiago': '(GMT-04:00) America/Santiago',
  'America/Santo_Domingo': '(GMT-04:00) America/Santo_Domingo',
  'America/Sao_Paulo': '(GMT-03:00) America/Sao_Paulo',
  'America/Scoresbysund': '(GMT-01:00) America/Scoresbysund',
  'America/Sitka': '(GMT-09:00) America/Sitka',
  'America/St_Johns': '(GMT-03:30) America/St_Johns',
  'America/Swift_Current': '(GMT-06:00) America/Swift_Current',
  'America/Tegucigalpa': '(GMT-06:00) America/Tegucigalpa',
  'America/Thule': '(GMT-04:00) America/Thule',
  'America/Thunder_Bay': '(GMT-05:00) America/Thunder_Bay',
  'America/Tijuana': '(GMT-08:00) America/Tijuana',
  'America/Toronto': '(GMT-05:00) America/Toronto',
  'America/Vancouver': '(GMT-08:00) America/Vancouver',
  'America/Whitehorse': '(GMT-07:00) America/Whitehorse',
  'America/Winnipeg': '(GMT-06:00) America/Winnipeg',
  'America/Yakutat': '(GMT-09:00) America/Yakutat',
  'America/Yellowknife': '(GMT-07:00) America/Yellowknife',
  'Antarctica/Casey': '(GMT+11:00) Antarctica/Casey',
  'Antarctica/Davis': '(GMT+07:00) Antarctica/Davis',
  'Antarctica/Macquarie': '(GMT+10:00) Antarctica/Macquarie',
  'Antarctica/Mawson': '(GMT+05:00) Antarctica/Mawson',
  'Antarctica/Palmer': '(GMT-03:00) Antarctica/Palmer',
  'Antarctica/Rothera': '(GMT-03:00) Antarctica/Rothera',
  'Antarctica/Troll': '(GMT+00:00) Antarctica/Troll',
  'Antarctica/Vostok': '(GMT+06:00) Antarctica/Vostok',
  'Asia/Almaty': '(GMT+06:00) Asia/Almaty',
  'Asia/Amman': '(GMT+02:00) Asia/Amman',
  'Asia/Anadyr': '(GMT+12:00) Asia/Anadyr',
  'Asia/Aqtau': '(GMT+05:00) Asia/Aqtau',
  'Asia/Aqtobe': '(GMT+05:00) Asia/Aqtobe',
  'Asia/Ashgabat': '(GMT+05:00) Asia/Ashgabat',
  'Asia/Atyrau': '(GMT+05:00) Asia/Atyrau',
  'Asia/Baghdad': '(GMT+03:00) Asia/Baghdad',
  'Asia/Baku': '(GMT+04:00) Asia/Baku',
  'Asia/Bangkok': '(GMT+07:00) Asia/Bangkok',
  'Asia/Barnaul': '(GMT+07:00) Asia/Barnaul',
  'Asia/Beirut': '(GMT+02:00) Asia/Beirut',
  'Asia/Bishkek': '(GMT+06:00) Asia/Bishkek',
  'Asia/Brunei': '(GMT+08:00) Asia/Brunei',
  'Asia/Chita': '(GMT+09:00) Asia/Chita',
  'Asia/Choibalsan': '(GMT+08:00) Asia/Choibalsan',
  'Asia/Colombo': '(GMT+05:30) Asia/Colombo',
  'Asia/Damascus': '(GMT+02:00) Asia/Damascus',
  'Asia/Dhaka': '(GMT+06:00) Asia/Dhaka',
  'Asia/Dili': '(GMT+09:00) Asia/Dili',
  'Asia/Dubai': '(GMT+04:00) Asia/Dubai',
  'Asia/Dushanbe': '(GMT+05:00) Asia/Dushanbe',
  'Asia/Famagusta': '(GMT+02:00) Asia/Famagusta',
  'Asia/Gaza': '(GMT+02:00) Asia/Gaza',
  'Asia/Hebron': '(GMT+02:00) Asia/Hebron',
  'Asia/Ho_Chi_Minh': '(GMT+07:00) Asia/Ho_Chi_Minh',
  'Asia/Hong_Kong': '(GMT+08:00) Asia/Hong_Kong',
  'Asia/Hovd': '(GMT+07:00) Asia/Hovd',
  'Asia/Irkutsk': '(GMT+08:00) Asia/Irkutsk',
  'Asia/Jakarta': '(GMT+07:00) Asia/Jakarta',
  'Asia/Jayapura': '(GMT+09:00) Asia/Jayapura',
  'Asia/Jerusalem': '(GMT+02:00) Asia/Jerusalem',
  'Asia/Kabul': '(GMT+04:30) Asia/Kabul',
  'Asia/Kamchatka': '(GMT+12:00) Asia/Kamchatka',
  'Asia/Karachi': '(GMT+05:00) Asia/Karachi',
  'Asia/Kathmandu': '(GMT+05:45) Asia/Kathmandu',
  'Asia/Khandyga': '(GMT+09:00) Asia/Khandyga',
  'Asia/Kolkata': '(GMT+05:30) Asia/Kolkata',
  'Asia/Krasnoyarsk': '(GMT+07:00) Asia/Krasnoyarsk',
  'Asia/Kuala_Lumpur': '(GMT+08:00) Asia/Kuala_Lumpur',
  'Asia/Kuching': '(GMT+08:00) Asia/Kuching',
  'Asia/Macau': '(GMT+08:00) Asia/Macau',
  'Asia/Magadan': '(GMT+11:00) Asia/Magadan',
  'Asia/Makassar': '(GMT+08:00) Asia/Makassar',
  'Asia/Manila': '(GMT+08:00) Asia/Manila',
  'Asia/Nicosia': '(GMT+02:00) Asia/Nicosia',
  'Asia/Novokuznetsk': '(GMT+07:00) Asia/Novokuznetsk',
  'Asia/Novosibirsk': '(GMT+07:00) Asia/Novosibirsk',
  'Asia/Omsk': '(GMT+06:00) Asia/Omsk',
  'Asia/Oral': '(GMT+05:00) Asia/Oral',
  'Asia/Pontianak': '(GMT+07:00) Asia/Pontianak',
  'Asia/Pyongyang': '(GMT+09:00) Asia/Pyongyang',
  'Asia/Qatar': '(GMT+03:00) Asia/Qatar',
  'Asia/Qostanay': '(GMT+06:00) Asia/Qostanay',
  'Asia/Qyzylorda': '(GMT+05:00) Asia/Qyzylorda',
  'Asia/Riyadh': '(GMT+03:00) Asia/Riyadh',
  'Asia/Sakhalin': '(GMT+11:00) Asia/Sakhalin',
  'Asia/Samarkand': '(GMT+05:00) Asia/Samarkand',
  'Asia/Seoul': '(GMT+09:00) Asia/Seoul',
  'Asia/Shanghai': '(GMT+08:00) Asia/Shanghai',
  'Asia/Singapore': '(GMT+08:00) Asia/Singapore',
  'Asia/Srednekolymsk': '(GMT+11:00) Asia/Srednekolymsk',
  'Asia/Taipei': '(GMT+08:00) Asia/Taipei',
  'Asia/Tashkent': '(GMT+05:00) Asia/Tashkent',
  'Asia/Tbilisi': '(GMT+04:00) Asia/Tbilisi',
  'Asia/Tehran': '(GMT+03:30) Asia/Tehran',
  'Asia/Thimphu': '(GMT+06:00) Asia/Thimphu',
  'Asia/Tokyo': '(GMT+09:00) Asia/Tokyo',
  'Asia/Tomsk': '(GMT+07:00) Asia/Tomsk',
  'Asia/Ulaanbaatar': '(GMT+08:00) Asia/Ulaanbaatar',
  'Asia/Urumqi': '(GMT+06:00) Asia/Urumqi',
  'Asia/Ust-Nera': '(GMT+10:00) Asia/Ust-Nera',
  'Asia/Vladivostok': '(GMT+10:00) Asia/Vladivostok',
  'Asia/Yakutsk': '(GMT+09:00) Asia/Yakutsk',
  'Asia/Yangon': '(GMT+06:30) Asia/Yangon',
  'Asia/Yekaterinburg': '(GMT+05:00) Asia/Yekaterinburg',
  'Asia/Yerevan': '(GMT+04:00) Asia/Yerevan',
  'Atlantic/Azores': '(GMT-01:00) Atlantic/Azores',
  'Atlantic/Bermuda': '(GMT-04:00) Atlantic/Bermuda',
  'Atlantic/Canary': '(GMT+00:00) Atlantic/Canary',
  'Atlantic/Cape_Verde': '(GMT-01:00) Atlantic/Cape_Verde',
  'Atlantic/Faroe': '(GMT+00:00) Atlantic/Faroe',
  'Atlantic/Madeira': '(GMT+00:00) Atlantic/Madeira',
  'Atlantic/Reykjavik': '(GMT+00:00) Atlantic/Reykjavik',
  'Atlantic/South_Georgia': '(GMT-02:00) Atlantic/South_Georgia',
  'Atlantic/Stanley': '(GMT-03:00) Atlantic/Stanley',
  'Australia/Adelaide': '(GMT+09:30) Australia/Adelaide',
  'Australia/Brisbane': '(GMT+10:00) Australia/Brisbane',
  'Australia/Broken_Hill': '(GMT+09:30) Australia/Broken_Hill',
  'Australia/Darwin': '(GMT+09:30) Australia/Darwin',
  'Australia/Eucla': '(GMT+08:45) Australia/Eucla',
  'Australia/Hobart': '(GMT+10:00) Australia/Hobart',
  'Australia/Lindeman': '(GMT+10:00) Australia/Lindeman',
  'Australia/Lord_Howe': '(GMT+10:30) Australia/Lord_Howe',
  'Australia/Melbourne': '(GMT+10:00) Australia/Melbourne',
  'Australia/Perth': '(GMT+08:00) Australia/Perth',
  'Australia/Sydney': '(GMT+10:00) Australia/Sydney',
  'Europe/Amsterdam': '(GMT+01:00) Europe/Amsterdam',
  'Europe/Andorra': '(GMT+01:00) Europe/Andorra',
  'Europe/Astrakhan': '(GMT+04:00) Europe/Astrakhan',
  'Europe/Athens': '(GMT+02:00) Europe/Athens',
  'Europe/Belgrade': '(GMT+01:00) Europe/Belgrade',
  'Europe/Berlin': '(GMT+01:00) Europe/Berlin',
  'Europe/Brussels': '(GMT+01:00) Europe/Brussels',
  'Europe/Bucharest': '(GMT+02:00) Europe/Bucharest',
  'Europe/Budapest': '(GMT+01:00) Europe/Budapest',
  'Europe/Chisinau': '(GMT+02:00) Europe/Chisinau',
  'Europe/Copenhagen': '(GMT+01:00) Europe/Copenhagen',
  'Europe/Dublin': '(GMT+00:00) Europe/Dublin',
  'Europe/Gibraltar': '(GMT+01:00) Europe/Gibraltar',
  'Europe/Helsinki': '(GMT+02:00) Europe/Helsinki',
  'Europe/Istanbul': '(GMT+03:00) Europe/Istanbul',
  'Europe/Kaliningrad': '(GMT+02:00) Europe/Kaliningrad',
  'Europe/Kiev': '(GMT+02:00) Europe/Kiev',
  'Europe/Kirov': '(GMT+03:00) Europe/Kirov',
  'Europe/Lisbon': '(GMT+00:00) Europe/Lisbon',
  'Europe/London': '(GMT+00:00) Europe/London',
  'Europe/Luxembourg': '(GMT+01:00) Europe/Luxembourg',
  'Europe/Madrid': '(GMT+01:00) Europe/Madrid',
  'Europe/Malta': '(GMT+01:00) Europe/Malta',
  'Europe/Minsk': '(GMT+03:00) Europe/Minsk',
  'Europe/Monaco': '(GMT+01:00) Europe/Monaco',
  'Europe/Moscow': '(GMT+03:00) Europe/Moscow',
  'Europe/Oslo': '(GMT+01:00) Europe/Oslo',
  'Europe/Paris': '(GMT+01:00) Europe/Paris',
  'Europe/Prague': '(GMT+01:00) Europe/Prague',
  'Europe/Riga': '(GMT+02:00) Europe/Riga',
  'Europe/Rome': '(GMT+01:00) Europe/Rome',
  'Europe/Samara': '(GMT+04:00) Europe/Samara',
  'Europe/Saratov': '(GMT+04:00) Europe/Saratov',
  'Europe/Simferopol': '(GMT+03:00) Europe/Simferopol',
  'Europe/Sofia': '(GMT+02:00) Europe/Sofia',
  'Europe/Stockholm': '(GMT+01:00) Europe/Stockholm',
  'Europe/Tallinn': '(GMT+02:00) Europe/Tallinn',
  'Europe/Tirane': '(GMT+01:00) Europe/Tirane',
  'Europe/Ulyanovsk': '(GMT+04:00) Europe/Ulyanovsk',
  'Europe/Uzhgorod': '(GMT+02:00) Europe/Uzhgorod',
  'Europe/Vienna': '(GMT+01:00) Europe/Vienna',
  'Europe/Vilnius': '(GMT+02:00) Europe/Vilnius',
  'Europe/Volgograd': '(GMT+03:00) Europe/Volgograd',
  'Europe/Warsaw': '(GMT+01:00) Europe/Warsaw',
  'Europe/Zaporozhye': '(GMT+02:00) Europe/Zaporozhye',
  'Europe/Zurich': '(GMT+01:00) Europe/Zurich',
  'Indian/Chagos': '(GMT+06:00) Indian/Chagos',
  'Indian/Christmas': '(GMT+07:00) Indian/Christmas',
  'Indian/Cocos': '(GMT+06:30) Indian/Cocos',
  'Indian/Kerguelen': '(GMT+05:00) Indian/Kerguelen',
  'Indian/Mahe': '(GMT+04:00) Indian/Mahe',
  'Indian/Maldives': '(GMT+05:00) Indian/Maldives',
  'Indian/Mauritius': '(GMT+04:00) Indian/Mauritius',
  'Indian/Reunion': '(GMT+04:00) Indian/Reunion',
  'Pacific/Apia': '(GMT+13:00) Pacific/Apia',
  'Pacific/Auckland': '(GMT+12:00) Pacific/Auckland',
  'Pacific/Bougainville': '(GMT+11:00) Pacific/Bougainville',
  'Pacific/Chatham': '(GMT+12:45) Pacific/Chatham',
  'Pacific/Chuuk': '(GMT+10:00) Pacific/Chuuk',
  'Pacific/Easter': '(GMT-06:00) Pacific/Easter',
  'Pacific/Efate': '(GMT+11:00) Pacific/Efate',
  'Pacific/Fakaofo': '(GMT+13:00) Pacific/Fakaofo',
  'Pacific/Fiji': '(GMT+12:00) Pacific/Fiji',
  'Pacific/Funafuti': '(GMT+12:00) Pacific/Funafuti',
  'Pacific/Galapagos': '(GMT-06:00) Pacific/Galapagos',
  'Pacific/Gambier': '(GMT-09:00) Pacific/Gambier',
  'Pacific/Guadalcanal': '(GMT+11:00) Pacific/Guadalcanal',
  'Pacific/Honolulu': '(GMT-10:00) Pacific/Honolulu',
  'Pacific/Kiritimati': '(GMT+14:00) Pacific/Kiritimati',
  'Pacific/Kosrae': '(GMT+11:00) Pacific/Kosrae',
  'Pacific/Kwajalein': '(GMT+12:00) Pacific/Kwajalein',
  'Pacific/Majuro': '(GMT+12:00) Pacific/Majuro',
  'Pacific/Marquesas': '(GMT-09:30) Pacific/Marquesas',
  'Pacific/Nauru': '(GMT+12:00) Pacific/Nauru',
  'Pacific/Niue': '(GMT-11:00) Pacific/Niue',
  'Pacific/Norfolk': '(GMT+11:00) Pacific/Norfolk',
  'Pacific/Noumea': '(GMT+11:00) Pacific/Noumea',
  'Pacific/Pago_Pago': '(GMT-11:00) Pacific/Pago_Pago',
  'Pacific/Palau': '(GMT+09:00) Pacific/Palau',
  'Pacific/Pitcairn': '(GMT-08:00) Pacific/Pitcairn',
  'Pacific/Pohnpei': '(GMT+11:00) Pacific/Pohnpei',
  'Pacific/Port_Moresby': '(GMT+10:00) Pacific/Port_Moresby',
  'Pacific/Rarotonga': '(GMT-10:00) Pacific/Rarotonga',
  'Pacific/Tahiti': '(GMT-10:00) Pacific/Tahiti',
  'Pacific/Tarawa': '(GMT+12:00) Pacific/Tarawa',
  'Pacific/Tongatapu': '(GMT+13:00) Pacific/Tongatapu',
  'Pacific/Wake': '(GMT+12:00) Pacific/Wake',
  'Pacific/Wallis': '(GMT+12:00) Pacific/Wallis',
};

export type TimezoneInfo = {
  id: string;
  name: string;
  offset: number;
  city: string;
  label: string;
};

// Parse offset from string like "(GMT+07:00)" or "(GMT-05:00)"
const parseOffset = (text: string): number => {
  const match = text.match(/GMT([+-])(\d{2}):(\d{2})/);
  if (!match) return 0;
  const sign = match[1] === '+' ? 1 : -1;
  const hours = parseInt(match[2], 10);
  const minutes = parseInt(match[3], 10);
  return sign * (hours + minutes / 60);
};

// Extract city name from IANA timezone name
const extractCity = (ianaName: string): string => {
  const parts = ianaName.split('/');
  const city = parts[parts.length - 1];
  return city.replace(/_/g, ' ');
};

// Create unique ID from IANA name
const createId = (ianaName: string): string => {
  return ianaName.toLowerCase().replace(/\//g, '-').replace(/_/g, '-');
};

// Build the timezone list from TIMEZONES object
export const TIMEZONE_LIST: TimezoneInfo[] = Object.entries(TIMEZONES)
  .map(([ianaName, label]) => ({
    id: createId(ianaName),
    name: ianaName,
    offset: parseOffset(label),
    city: extractCity(ianaName),
    label,
  }))
  .sort((a, b) => {
    if (a.offset !== b.offset) return a.offset - b.offset;
    return a.city.localeCompare(b.city);
  });

export const getTimezoneById = (id: string): TimezoneInfo | undefined =>
  TIMEZONE_LIST.find((tz) => tz.id === id);

export const formatHour = (hour: number): string => {
  const h = Math.floor(hour) % 24;
  const suffix = h >= 12 ? 'PM' : 'AM';
  const displayHour = h === 0 ? 12 : h > 12 ? h - 12 : h;
  return `${displayHour}${suffix}`;
};

export const formatTime = (hour: number): string => {
  const h = Math.floor(hour) % 24;
  const m = Math.round((hour - Math.floor(hour)) * 60);
  const suffix = h >= 12 ? 'PM' : 'AM';
  const displayHour = h === 0 ? 12 : h > 12 ? h - 12 : h;
  return `${displayHour}:${m.toString().padStart(2, '0')} ${suffix}`;
};

export const isWorkingHour = (hour: number): boolean => hour >= 9 && hour < 18;

export const getCurrentUTCHour = (): number => {
  const now = new Date();
  return now.getUTCHours() + now.getUTCMinutes() / 60;
};

// Get current hour in a specific timezone (by offset)
export const getCurrentHourInTimezone = (offset: number): number => {
  const utcHour = getCurrentUTCHour();
  return ((utcHour + offset) % 24 + 24) % 24;
};
